name: Research CI/CD
on:
  push:
    branches:
      - research
  pull_request:
    branches:
      - research

env:
  CI: false
  # env_main: ${{secrets.ENV_MAIN}}

jobs:
  build-test:
    name: install dependencies & test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # - name: create environment file
      #   run: |
      #     touch ./.env && echo "$env_main" >> ./.env

      - name: install dependencies
        run: |
          yarn install

      - name: build react app
        run: |
          yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push
        id: build-push
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rumsan/giga_docs:research
          

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .
